---
# Enable captive portal:
captive_portal:

# Enable API
api:

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Esphome setup
esphome:
  name: oven_1
  platform: ESP8266
  board: d1_mini

# Modules setup
spi:
  miso_pin: D1
  clk_pin: D2

sensor:
  - platform: max6675
    name: Oven Temperature
    cs_pin: D3
    update_interval: 60s

switch:
  - platform: gpio
    name: Oven on/off
    pin: D5
