---
# Enable captive portal:
captive_portal:

# Enable API
api:

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Esphome setup
esphome:
  name: oven_1
  platform: ESP8266
  board: d1_mini

# Modules setup
spi:
  miso_pin: D1
  clk_pin: D2

sensor:
  - platform: max6675
    name: Oven Temperature
    id: temperature
    cs_pin: D3
    update_interval: 60s

switch:
  - platform: gpio
    name: Oven Heater
    id: heater
    pin: D5

climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: oven_temperature
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 °C