---
# Enable captive portal:
captive_portal:

# Enable webserver
web_server:
  port: 80
  css_url: https://kiln-controller.s3.eu-central-1.amazonaws.com/index.css
  js_url: https://kiln-controller.s3.eu-central-1.amazonaws.com/index.js

# Enable ota
ota:
  password: !secret ota_password

# Enable logging
logger:
  level: INFO

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Enable wifi
wifi:
  ap: {}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Esphome setup
esphome:
  name: glas-kiln
  platform: ESP8266
  board: d1_mini
  # based on this https://community.platformio.org/t/which-c-standard-am-i-using/24597/4
  # get higher c++ standard, mostly for std::to_array
  platformio_options:
    build_flags:
      - -std=gnu++20
    build_unflags:
      - -std=gnu++17

# Modules setup
spi:
  miso_pin: D2
  clk_pin: D4

# Setup API
kiln_api:
external_components:
  - source: github://kiln-controller/esphome-kiln-api@main
  # - source:
  #     type: local
  #     path: components/

# Kiln
output:
  - platform: slow_pwm
    id: heater
    period: 15s
    pin: D1

sensor:
  - platform: max6675
    name: Kiln Temperature
    id: kiln_temperature
    cs_pin: D3
    update_interval: 1s
  # NOTE: just for testing
  # - platform: template
  #   name: Kiln Temperature
  #   id: kiln_temperature
  #   update_interval: 10s
  #   lambda: |-
  #     return id(kiln).target_temperature;

climate:
  - platform: pid
    id: kiln  # is referenced in kiln_api, keep this
    name: Kiln
    sensor: kiln_temperature
    default_target_temperature: "0"
    visual:
      min_temperature: 0
      max_temperature: 1500
      temperature_step: 0.1
    heat_output: heater
    deadband_parameters:
      threshold_high: 0.5°C
      threshold_low: -1.0°C
      kp_multiplier: 0.0   # proportional gain turned off inside deadband
      ki_multiplier: 0.05  # integral accumulates at only 5% of normal ki
      kd_multiplier: 0.0   # derviative is turned off inside deadband
      deadband_output_averaging_samples: 15   # average the output over 15 samples within the deadband
    control_parameters:
      kp: 0.10913
      ki: 0.00647
      kd: 0.45992
