homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.9187
  longitude: 4.4759
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

frontend:

# Set database path
recorder:
  db_url: postgresql://hass:password@postgres/home_assistant_db

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Need to get past onboarding
config:


# Android app integration
mobile_app:
# Needed otherwise the app registration errors
cloud:

lovelace:
  mode: yaml
  resources:
    - url: /local/scheduler-card/scheduler-card.js?v=0
      type: module

climate:
  - platform: generic_thermostat
    name: Oven1
    heater: switch.study_heater
    target_sensor: sensor.study_temperature
    min_temp: 0
    max_temp: 400
